/**
 * Mock / seed data for development without real API keys.
 * Activated when NEXT_PUBLIC_USE_MOCK_DATA=true
 */

import { Niche, TrendingVideo, Trend, VideoBrief } from '@/types';

export const MOCK_NICHES: Niche[] = [
  {
    id: 'niche-1',
    name: 'AI & Machine Learning',
    description: 'Tutorials, tools, and news in AI/ML space',
    keywords: ['ai', 'machine learning', 'chatgpt', 'llm', 'stable diffusion', 'copilot'],
    color: '#6366f1',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'niche-2',
    name: 'Personal Finance',
    description: 'Investing, budgeting, FIRE, wealth building',
    keywords: ['investing', 'stocks', 'etf', 'budget', 'fire', 'passive income'],
    color: '#10b981',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'niche-3',
    name: 'Web Development',
    description: 'Frontend, backend, and full-stack tutorials',
    keywords: ['react', 'nextjs', 'typescript', 'css', 'api', 'devops'],
    color: '#f59e0b',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'niche-4',
    name: 'Productivity & Tools',
    description: 'Workflows, apps, and systems for getting things done',
    keywords: ['notion', 'obsidian', 'productivity', 'automation', 'zapier'],
    color: '#8b5cf6',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

export const MOCK_TRENDING_VIDEOS: TrendingVideo[] = [
  {
    id: 'video-1',
    youtube_id: 'dQw4w9WgXcQ',
    title: 'I Built a Full AI Agent in 30 Minutes with Claude',
    description: 'Complete walkthrough of building an autonomous AI agent using Claude API and tool use.',
    thumbnail_url: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    channel_id: 'UC123',
    channel_name: 'TechWithTim',
    channel_subscribers: 42000,
    view_count: 284000,
    like_count: 12400,
    comment_count: 890,
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    days_since_published: 3,
    velocity_score: 92,
    core_topic: 'building AI agents with Claude',
    transcript_summary:
      'Tutorial on building a multi-step AI agent using Anthropic Claude API with tool calling, covering setup, tool definition, and orchestration patterns.',
    comment_requests: ['do a video on memory systems for agents', 'show how to add search tools'],
    niche_id: 'niche-1',
    captured_at: new Date().toISOString(),
  },
  {
    id: 'video-2',
    youtube_id: 'abc123def',
    title: 'OpenAI vs Claude vs Gemini — Which LLM Should You Build With?',
    description: 'Comprehensive comparison of top LLMs for developers in 2025.',
    thumbnail_url: 'https://i.ytimg.com/vi/abc123def/hqdefault.jpg',
    channel_id: 'UC456',
    channel_name: 'AI Explained',
    channel_subscribers: 118000,
    view_count: 520000,
    like_count: 24500,
    comment_count: 3200,
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    days_since_published: 5,
    velocity_score: 88,
    core_topic: 'LLM comparison for developers',
    transcript_summary: 'Benchmark comparison of OpenAI GPT-4o, Claude 3.5, and Gemini 1.5 across coding, reasoning, and cost benchmarks.',
    comment_requests: ['compare pricing models too', 'do a video on context windows'],
    niche_id: 'niche-1',
    captured_at: new Date().toISOString(),
  },
  {
    id: 'video-3',
    youtube_id: 'xyz789abc',
    title: 'Local LLMs Are Getting Scary Good (Ollama + Llama 3.2 Deep Dive)',
    description: 'Running powerful models locally with Ollama — privacy, speed, and zero cost.',
    thumbnail_url: 'https://i.ytimg.com/vi/xyz789abc/hqdefault.jpg',
    channel_id: 'UC789',
    channel_name: 'Pratical AI',
    channel_subscribers: 28000,
    view_count: 198000,
    like_count: 9800,
    comment_count: 1450,
    published_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    days_since_published: 4,
    velocity_score: 95,
    core_topic: 'local LLMs with Ollama',
    transcript_summary: 'Setup guide for running Llama 3.2 locally using Ollama, covering installation, performance tips, and integration with LangChain.',
    comment_requests: ['show how to use with Python', 'can you benchmark vs GPT-4?'],
    niche_id: 'niche-1',
    captured_at: new Date().toISOString(),
  },
  {
    id: 'video-4',
    youtube_id: 'fin001abc',
    title: 'The Index Fund Strategy That Made Me $1M by 35',
    description: 'Exactly how I invested in low-cost index funds to reach financial independence.',
    thumbnail_url: 'https://i.ytimg.com/vi/fin001abc/hqdefault.jpg',
    channel_id: 'UC_FIN1',
    channel_name: 'Graham Stephan',
    channel_subscribers: 3800000,
    view_count: 1200000,
    like_count: 45000,
    comment_count: 8900,
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    days_since_published: 2,
    velocity_score: 71,
    core_topic: 'index fund investing for FIRE',
    transcript_summary: 'Personal finance walkthrough of index fund investing strategy, asset allocation, and rebalancing for financial independence.',
    comment_requests: ['what about international funds?', 'do a video on tax loss harvesting'],
    niche_id: 'niche-2',
    captured_at: new Date().toISOString(),
  },
  {
    id: 'video-5',
    youtube_id: 'fin002abc',
    title: 'I Invested $500/month for 10 Years — Here Are My Real Returns',
    description: 'Real portfolio performance data from 10 years of consistent DCA investing.',
    thumbnail_url: 'https://i.ytimg.com/vi/fin002abc/hqdefault.jpg',
    channel_id: 'UC_FIN2',
    channel_name: 'Humphrey Yang',
    channel_subscribers: 1200000,
    view_count: 380000,
    like_count: 18000,
    comment_count: 2400,
    published_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    days_since_published: 6,
    velocity_score: 65,
    core_topic: 'dollar cost averaging real results',
    transcript_summary: 'Transparent breakdown of 10 years of DCA investing results in Vanguard index funds with actual account screenshots.',
    comment_requests: ['show your full portfolio breakdown', 'do a video on bonds allocation'],
    niche_id: 'niche-2',
    captured_at: new Date().toISOString(),
  },
];

export const MOCK_TRENDS: Trend[] = [
  {
    id: 'trend-1',
    topic: 'Local LLMs and Privacy-First AI',
    source: 'combined',
    momentum_score: 87,
    opportunity_score: 94,
    tweet_count: 18400,
    twitter_query: 'local llm ollama llama privacy',
    related_video_ids: ['video-3'],
    niche_id: 'niche-1',
    detected_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 42 * 60 * 60 * 1000).toISOString(),
    related_videos: [MOCK_TRENDING_VIDEOS[2]],
  },
  {
    id: 'trend-2',
    topic: 'AI Agent Frameworks for Beginners',
    source: 'combined',
    momentum_score: 82,
    opportunity_score: 89,
    tweet_count: 12200,
    twitter_query: 'ai agent langchain claude openai tool use',
    related_video_ids: ['video-1'],
    niche_id: 'niche-1',
    detected_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 36 * 60 * 60 * 1000).toISOString(),
    related_videos: [MOCK_TRENDING_VIDEOS[0]],
  },
  {
    id: 'trend-3',
    topic: 'LLM Model Comparison 2025',
    source: 'youtube',
    momentum_score: 75,
    opportunity_score: 78,
    tweet_count: 8900,
    twitter_query: 'gpt4 vs claude gemini comparison',
    related_video_ids: ['video-2'],
    niche_id: 'niche-1',
    detected_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 30 * 60 * 60 * 1000).toISOString(),
    related_videos: [MOCK_TRENDING_VIDEOS[1]],
  },
  {
    id: 'trend-4',
    topic: 'Index Fund Millionaire Strategies',
    source: 'combined',
    momentum_score: 79,
    opportunity_score: 83,
    tweet_count: 21000,
    twitter_query: 'index fund millionaire fire investing',
    related_video_ids: ['video-4', 'video-5'],
    niche_id: 'niche-2',
    detected_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 40 * 60 * 60 * 1000).toISOString(),
    related_videos: [MOCK_TRENDING_VIDEOS[3], MOCK_TRENDING_VIDEOS[4]],
  },
];

export const MOCK_BRIEFS: VideoBrief[] = [
  {
    id: 'brief-1',
    topic: 'Local LLMs and Privacy-First AI',
    title_suggestions: [
      'Run AI Locally — Zero Cost, Zero Privacy Risk (Ollama Guide)',
      'Local LLMs Are Better Than Cloud AI (Here\'s Why)',
      'I Switched from ChatGPT to Local AI — Here\'s What Happened',
      'Llama 3.2 on Your Laptop: The Complete Setup Guide 2025',
      'Why Privacy-First AI Will Replace Cloud Models',
    ],
    hook:
      "Stop sending your private data to Big Tech servers. In the next 15 minutes, I'm going to show you how to run a model that rivals GPT-4 — completely locally, completely free, and no one can see what you're asking.",
    outline: [
      {
        point: 1,
        heading: 'Why Local AI is a Game Changer',
        notes: 'Privacy concerns with cloud AI, API costs at scale, offline usage, speed comparison',
      },
      {
        point: 2,
        heading: 'Setting Up Ollama in 5 Minutes',
        notes: 'Installation on Mac/Windows/Linux, first model download, CLI basics',
      },
      {
        point: 3,
        heading: 'Which Model Should You Run?',
        notes: 'Llama 3.2, Mistral, Phi-3 comparison, when to use each, hardware requirements',
      },
      {
        point: 4,
        heading: 'Real-World Use Cases',
        notes: 'Code assistant, writing, data analysis, document Q&A — all locally',
      },
      {
        point: 5,
        heading: 'Limitations and When to Use Cloud',
        notes: 'Hardware constraints, multimodal tasks, when cloud still wins, hybrid approach',
      },
    ],
    thumbnail_concept:
      'Split-screen: left side shows ominous cloud with "YOUR DATA" text, right side shows laptop with green checkmark and "LOCAL & PRIVATE". Bold red text overlay: "BIG TECH CAN\'T SEE THIS".',
    tags: ['ollama', 'local llm', 'llama3', 'private ai', 'chatgpt alternative', 'ai tutorial', 'machine learning', 'open source ai', 'self-hosted ai', 'ai privacy'],
    niche_id: 'niche-1',
    trend_id: 'trend-1',
    source_video_ids: ['video-3'],
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
];

// Helper to check if mock mode is enabled
export function isMockMode(): boolean {
  return process.env.NEXT_PUBLIC_USE_MOCK_DATA === 'true';
}
